security:
  basic:
    enabled: true

server:
  port: 8081
  context-path: /hotel-booking
  ssl:
    enabled: false
  tomcat:
    basedir: ${hotelbooking.tomcat.workdir}
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

spring:
  application:
    name: rexis-hotel-booking
  datasource:
    url: ${hotelbooking.database.url}
    username: ${hotelbooking.database.username}
    password: ${hotelbooking.database.password}

info:
  version: 0.1.0
  os: ${os.name}
