security:
  basic:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /hotel-booking
  ssl:
    enabled: false
  tomcat:
    basedir: tomcat-workdir
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

spring:
  application:
    name: rexis-hotel-booking
  datasource:
    url: ${hotelbooking.database.url}
    username: ${hotelbooking.database.username}
    password: ${hotelbooking.database.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    allow-bean-definition-overriding: true

info:
  version: 0.1.0
  os: ${os.name}

management:
  endpoints:
    web:
      base-path: /actuator

logging:
  ignorepattern: '(\/hotel-booking)?\/(css|fonts|images|js|locales)\/.*'
  level:
    info.rexis.hotelbooking.web.logging.RegexedRequestLoggingFilter: DEBUG
    info.rexis.hotelbooking.repositories.regsys.feign.RegsysFeignClient: DEBUG
    info.rexis.hotelbooking.web.AppErrorController: INFO
