security:
  basic:
    enabled: true

server:
  port: 8081
  context-path: /hotel-booking
  ssl:
    enabled: false
  tomcat:
    basedir: tomcat-workdir
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

spring:
  application:
    name: rexis-hotel-booking
  datasource:
    url: ${hotelbooking.database.url}
    username: ${hotelbooking.database.username}
    password: ${hotelbooking.database.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

info:
  version: 0.1.0
  os: ${os.name}

management:
  context-path: /actuator
  security:
    enabled: true
    roles: ADMIN

logging:
  ignorepattern: '(\/hotel-booking)?\/(css|fonts|images|js|locales)\/.*'
  level:
    info.rexis.hotelbooking.web.config.RegexedRequestLoggingFilter: DEBUG
    info.rexis.hotelbooking.repositories.regsys.feign.RegsysFeignClient: DEBUG
    info.rexis.hotelbooking.web.AppErrorController: INFO
