hotelinfo:
  roomtypes:
    - name: Concert Hall
      value: standard
      description: a concert hall built in stone
      infolink: http://localhost/concerthall
      price1: 84.00
      price2: 99.00
      price3: 104.00
    - name: Stadium
      value: stadium
      description: a stadium out in the open
      infolink: http://localhost/stadium
      price1: 85.00
      price2: 100.00
      price3: 105.00
    - name: Shack in the Wilderness
      value: shack
      description: a wooden shack, well, at least it's dry
      infolink: http://localhost/shack
      price1: 14.00
      price2: 15.00
      price3: 19.00
  recipient: demo@mailinator.com
  stichwort: Demo Convention

regsys:
  uri: http://localhost:8080/regsys
  auth: demoAuth
  relaxedSsl: true

hotelbooking:
  database:
    url: jdbc:mysql://localhost/ef24rooms?useSSL=false
    username: ef-rooms
    password: demoDbPw
  admin:
    pw: demoPw
  user:
    pw: demoPw
