security:
  basic:
    enabled: true

server:
  port: 8081
  context-path: /hotel-booking
  ssl:
    enabled: false
  tomcat:
    basedir: tomcat-workdir
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

spring:
  application:
    name: rexis-hotel-booking

info:
  version: 0.1.0
  os: ${os.name}

logging:
  ignorepattern: '(\/hotel-booking)?\/(css|fonts|images|js|locales)\/.*'
  level:
    info.rexis.hotelbooking.web.config.RegexedRequestLoggingFilter: DEBUG
    info.rexis.hotelbooking.repositories.regsys.feign.RegsysFeignClient: DEBUG
    info.rexis.hotelbooking.web.AppErrorController: INFO
