security:
  basic:
    enabled: true

server:
  port: 8081
  ssl:
    enabled: false

spring:
  application:
    name: rexis-hotel-booking
  datasource:
    url: ${hotelbooking.database.url}
    username: ${hotelbooking.database.username}
    password: ${hotelbooking.database.password}

info:
  version: @version@
  os: ${os.name}
